### ISSUE TITLE
Hotspot status duplicate?

### ISSUE THREAD

**Issue by DevJelle** [hotspotty/documentation#16]
It looks like 'Hotspot status' can get removed from the Getting Started section because @dansku already wrote a very good page in 'Advanced' or is 'Hotspot status' supposed to include other information?

Status check in 'Advanced': https://docs.hotspotty.net/expand-the-network/status-checker

Hotspot status in 'Getting started': https://docs.hotspotty.net/getting-started/hotspot-status

**Comment by dansku** [comment]
@DevJelle good point!!

You know what I was thinking about, inside `getting started`, instead of `hotspot-status` we could have a page dedicated to the hotspot, going though each tab and explaining the content or linking to them if they are in other pages.

![image](https://user-images.githubusercontent.com/590207/148640071-0c13d1a1-54b0-489b-9db3-507b8f5c86d2.png)

what do you think?

**Comment by DevJelle** [comment]
Cool, yeah that sounds great! Not sure if we should change the name of it then. We'll see.
